// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX79mHgKM4WlC038CpjryftgbInv7lZTc',
    appId: '1:412415548973:web:3fa46834872bbcb91122a4',
    messagingSenderId: '412415548973',
    projectId: 'walle-1a82c',
    authDomain: 'walle-1a82c.firebaseapp.com',
    storageBucket: 'walle-1a82c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcRM_oYQnUmcE4tHBfLqP5TPu9ABF-_mM',
    appId: '1:412415548973:android:99ebf0ef7a5aede91122a4',
    messagingSenderId: '412415548973',
    projectId: 'walle-1a82c',
    storageBucket: 'walle-1a82c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnWYU1gQfbLgNpaLumW8oCHlNRlcxwOZY',
    appId: '1:412415548973:ios:ba40916d4a49be991122a4',
    messagingSenderId: '412415548973',
    projectId: 'walle-1a82c',
    storageBucket: 'walle-1a82c.appspot.com',
    iosBundleId: 'com.example.walleFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnWYU1gQfbLgNpaLumW8oCHlNRlcxwOZY',
    appId: '1:412415548973:ios:ba40916d4a49be991122a4',
    messagingSenderId: '412415548973',
    projectId: 'walle-1a82c',
    storageBucket: 'walle-1a82c.appspot.com',
    iosBundleId: 'com.example.walleFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX79mHgKM4WlC038CpjryftgbInv7lZTc',
    appId: '1:412415548973:web:cf8411f4a9f22dc61122a4',
    messagingSenderId: '412415548973',
    projectId: 'walle-1a82c',
    authDomain: 'walle-1a82c.firebaseapp.com',
    storageBucket: 'walle-1a82c.appspot.com',
  );
}
